name: Update README with Latest Repos

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install axios

    - name: Update README
      run: node scripts/update-readme.js

    - name: Stage changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md package.json  # Add any other files you need to commit

    - name: Commit changes
      run: |
        if ! git diff --cached --quiet; then  # Check if there are staged changes
          git commit -m "Updated README with recent repos and activities"
          git push
        else
          echo "No changes to commit"
        fi
